# Generated by Django 4.2.11 on 2025-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyChatBot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
