# Generated by Django 4.0.10 on 2025-10-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyChatBot', '0002_remove_doctor_hospital_remove_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('bp', models.CharField(blank=True, max_length=50, null=True)),
                ('diabetic', models.CharField(blank=True, max_length=50, null=True)),
                ('hyperthyroidism', models.CharField(blank=True, max_length=50, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('report_urls', models.TextField()),
                ('ai_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
